### ISSUE TITLE
Component menu dissapears in Joomla 3.4

### ISSUE THREAD

**Issue by lopezsalexander** [projectfork/Projectfork#1545]
Today I update my Joomla site to 3.4 version, but after update Projectfork in component menu dissapears, the only way for acces is index.php?option=com_projectfork. I purgue cache and still fail.

**Comment by eaxs** [comment]
I've updated too, but still have my menus as they were before. Fixing a broken menu structure is unfortunately not trivial. What you could try though, is to install Projectfork again on top of your existing install (don't uninstall). This may restore the menu. But take a complete site backup before doing this!

**Comment by eaxs** [comment]
Forget what I said above, it's something with how PF creates the menu items and Joomla 3.4 doesn't seem to like it :(

**Comment by Themoulos** [comment]
I am new to Joomla and Projectfork, so maybe it is nothing to do with this problem, but when I try to install (the latest version of) the extension, I get an error that an .xml file cannot be copied to its proper position. 
Here is what I get:
==============================
Warning

Copy failed.

JInstaller: :Install: Failed to copy file /var/www/vhosts/manpapad.gr/httpdocs/joomla/tmp/install_54f9a3d0a6ec6/Projectfork-4.2.2/source/pkg_projectfork.xml to /var/www/vhosts/manpapad.gr/httpdocs/joomla/administrator/manifests/packages/pkg_projectfork.xml

Package Install: Could not copy setup file.
====================================

Yet, I am able to see the Projectfork components in Module Mananger and Plugin Manager. Does it have anything to do with this problem? Should I open another issue?

**Comment by eaxs** [comment]
This seems to be a different problem entirely. Please make sure the path `joomla/administrator/manifests/packages` is writable, then try again.

**Comment by Pikkolo** [comment]
I installed pkg_projectfork_4.2.2 on Joomla! 3.4.0 and no menu is addedd to the component list. Hope to hear from developers <3

**Comment by eaxs** [comment]
I'm still looking into the issue, sorry. This one turned out to be tougher than anticipated. In the meantime, the website got back online if you're looking for the documentation :)

**Comment by eaxs** [comment]
Alright, should be fixed now. If you'd like to test and confirm, grab the latest dev code as explained here: https://github.com/projectfork/Projectfork/wiki/Downloading-the-code

Let me know what results you get. Also note that the dev code contains some currently untested new features.

**Comment by jrnegronvidal1510** [comment]
It didn't  work for me. I uninstalled the program and install the new package. It still the same. I activated the module and the menu is there. But, the component and the dashboard are not there.

**Comment by eaxs** [comment]
Hey thanks for testing. Can you give this package another try? 
http://projectfork.net/tmp/pkg_projectfork_test.zip

And I assume we're talking about this menu here:
![menu](https://cloud.githubusercontent.com/assets/489521/6616645/5e3bd7d4-c8b0-11e4-8649-46e4d00a717a.jpg)
... just want to make sure

**Comment by jrnegronvidal1510** [comment]
Exactly that. It's doesn't show up. I will try again.

**Comment by jrnegronvidal1510** [comment]
The new package worked well. During the day I will make some testing to see everything is running well. Thanks. I really want to work with this Projectfork.

**Comment by eaxs** [comment]
I'll close this issue then. If you find that it's not fixed somewhere, somehow, please reopen it. Thanks!

**Comment by lopezsalexander** [comment]
Thanks a lot
