### ISSUE TITLE
Problem with the calendar

### ISSUE THREAD

**Issue by ingjjaa** [projectfork/Projectfork#1590]
Hi i think that one of the principal things are the calendar and how that could be solve, i'd probable talk about another topic which is so many talk about it, the calendar module sho the activities one day before, do that happen yet, has some one solve it ???

**Comment by eaxs** [comment]
I've released a new version of the calendar that should address this issue: http://www.projectfork.net/blog/13-releases/93-calendar-module-1-0-2

Please let me know if it worked. Thanks!

**Comment by ingjjaa** [comment]
Sorry the problem is still present in the grantt cgart the date is the correct but in the calendar is one day before

**Comment by eaxs** [comment]
Hmm ok. Could you email support@projectfork.net with a login to your site so I can take a closer look?

**Comment by eaxs** [comment]
A new version (1.0.3) is now available for download. This will fix the issue once and for all I hope :)
http://projectfork.net/blog/13-releases/94-calendar-1-0-3-and-gantt-1-1-0-released
